### ISSUE TITLE
[rtve] detect and download 1080p videos.

### ISSUE THREAD

**Issue by felisucoibi** [blackjack4494/youtube-dlc#101]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description
Rtve.es now offers 1080p videos, but youtube-dl don't detects them just 570p vídeos.

Example:
https://www.rtve.es/alacarta/videos/somos-cine/somos-cine-lobos-sucios/5635544/
There is this version in 1080p not detected by youtube-dl
https://rtve-mediavod.secure.footprint.net/resources/TE_GLESP/mp4/4/4/1596110130044.mp4?nvb=20200802101238&nva=20200802161238&token=0fb8508c97cc61df59aaa

**Comment by blackjack4494** [comment]
If lower qualities are recognised as you say it should be fairly easy to fix. Sounds like higher quality formats won't be extracted.

**Comment by hugohaa** [comment]
Tried to look a bit but unfortunately, it's region-blocked. :(

**Comment by lonemadmax** [comment]
Anything those of us with access can extract to help?

**Comment by blackjack4494** [comment]
I have made some progress where to find the details about the qualities. However I have clue how to extract the video url so far. Will need some testing.

**Comment by felisucoibi** [comment]
In this website they got the hd video plus the others, maybe can help this info
http://www.descargavideos.tv/
You paste this url
https://www.rtve.es/alacarta/videos/somos-cine/somos-cine-lobos-sucios/5635544/

and the results offers you hd 1080p and others options to download.

**Comment by felisucoibi** [comment]
If you need betatesting just askme

**Comment by hugohaa** [comment]
If you check this api url

rtve.es/api/videos/5635544.json

it will return all the info and template you want

For a FULLHD video, it has this template:

`{
            "identifier": 4465780,
            "filePath": "http://ztnr.rtve.es/ztnr/res/_PROVIDER_/video/hd_full/_TOKEN_",
            "preset": "HD_FULL",
            "filesize": 21445621,
            "type": "application/mp4",
            "duration": 6133014,
            "bitRate": 5500000,
            "bitRateUnit": "bps",
            "language": "es",
            "previewPath": "https://img2.rtve.es/imagenes/lobos-sucios/1596110129831.jpg",
            "height": 1080,
            "width": 1920
          }`

So, we will need only this provider and token to download it, I guess.

**Comment by felisucoibi** [comment]
thanks, I'll try to find a way to get this info.

**Comment by felisucoibi** [comment]
I'm trying to get these two variales, provider and token but i think they are hidden inside images and they use javascirpt to get them

**Comment by lonemadmax** [comment]
There are full URL (not the variables) in text chunks of a black png, and the decoding is already there in https://github.com/blackjack4494/youtube-dlc/blob/ac76f0002920ebc1e17d924b2375618fc95470df/youtube_dlc/extractor/rtve.py#L24

The code is getting `'http://www.rtve.es/ztnr/movil/thumbnail/%s/videos/%s.png' % (self._manager, video_id)`. Visiting the web with my browser, I got https://ztnr.rtve.es/ztnr/movil/thumbnail/banebdyede/videos/5635544.png?q=v2, so quite near. Both with and without the `q=v2` param you get 4 text chunks, but the decoding function only takes the first. The difference is with the parameter you get a quality name before the encoded URL, the part being removed in https://github.com/blackjack4494/youtube-dlc/blob/ac76f0002920ebc1e17d924b2375618fc95470df/youtube_dlc/extractor/rtve.py#L35-L37, but that only checks for `H??%`, and the values I get are:
- `HQ%%` (what is currently fetched) 1024x576 for that video
- `Alta%%` 640x360
- `HD_FULL%%` 1920x1080
- `Media%%` 480x270

Anyway, current code just gets the first and assumes it would have a `HQ%%` tag or none.

The js that extracts the data seems to be in https://js2.rtve.es/pages/rtve-player-app/3.8.0/js/rtveplayer/modules/ztnr/ztnrThumbnail.js. At least there's code for `tEXt` (the png text chunk signature) and `%%` (the quality - encoded URL separator).

**Comment by lonemadmax** [comment]
It seems the image generated for Chromecast has the resources in decreasing quality order, so you can get the 1080 version, if available, without a code change passing `--user-agent 'Mozilla/5.0 (CrKey armv7l 1.5.16041) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.0 Safari/537.36'`.
