### ISSUE TITLE
ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by df1paw** [blackjack4494/youtube-dlc#112]
Hi!
How to deal with this issue?
[download]   0.8% of 27.61MiB at  2.43MiB/s ETA 00:11[download] Got server HTTP error: Downloaded 239009 bytes, expected 28951844 bytes. Retrying (attempt 1 of 10)...
ERROR: Did not get any data blocks

Kind regards,
    Andreas

**Comment by blackjack4494** [comment]
No clue. Need some more informations. your youtube-dlc parameters with -v output would help.

**Comment by blackjack4494** [comment]
Will close this until new informations are added.
