### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by user0150** [blackjack4494/youtube-dlc#119]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

My version
```
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
```
When I try to download this video https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-35-i-know-hell-796213 using --hls-prefer-native this message appears 

```
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
```
But this does not happen when using youtube-dl 2020.09.14, I always use --hls-prefer-native on Crunchyroll, because sometimes when you download using ffmpeg you get this error.

```
[mpegts @ 000001469b2a7800] PES packet size mismatch
[mpegts @ 000001469b2a7800] Packet corrupt (stream = 0, dts = 13684001).
```
And because of that the video is missing parts or skipping parts. Another question I have is that when using --hls-prefer-native, this message appears when the download is finished, but it does not happen when using --hls-prefer-ffmpeg.

`[ffmpeg] Fixing malformed AAC bitstream in "Download\Re -ZERO -Starting Life in Another World- Episode 35 – I Know Hell.mp4"`

This is normal?

**Comment by blackjack4494** [comment]
Hm. Did you have any problems with last version (2020.09.13) or any other versions of youtube-dlc?  
Also this won't appear with youtube-dl?  
You could try adding `--ignore-dynamic-mpd` tho it is only related to dash so I don't think it would make a difference.  

It just seems a strange bug to me.  
Do you use any vpn? Can you provide me the m3u8 used by youtube-dlc and youtube-dl?  
If it won't be displayed in console you should be able to extract it if you use `--write-info-json`. Search in that file for `m3u8` oder `manifest`. Click the link and the manifest should download. You probably need to upload it somewhere or paste it into a gist/pastebin if it's not too big.
