### ISSUE TITLE
Pull/copy chapter extraction fixes from other youtube-dl fork

### ISSUE THREAD

**Issue by jbruchon** [blackjack4494/youtube-dlc#136]
https://github.com/pukkandan/youtube-dl/pull/6

**Comment by blackjack4494** [comment]
https://github.com/blackjack4494/youtube-dlc/blob/1f6cf75488dd786d5c6b38b324eceddb69fc1a5b/youtube_dlc/extractor/youtube.py#L1701-L1713

Those changes are already incorporated.

**Comment by jbruchon** [comment]
OK, sorry about that!
