### ISSUE TITLE
Is there a 32-Bit and a 64-Bit exe?

### ISSUE THREAD

**Issue by armyc84** [blackjack4494/youtube-dlc#143]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I am using the youtube-dlc.exe on the back-end of a program that I'm building an mpv player for. I have a very simple build, but it looks like the youtube-dlc.exe only executes on my 64-bit vm's. I was just curious to know if there was a 32-bit and 64-bit version of this youtube-dlc.exe?

**Comment by blackjack4494** [comment]
There is. However the new workflow got some minor flaws so 32 Bit didn't get build this time. But will add it manually (maybe today or later). Do note tho that I will name the 32 Bit version `youtube-dlc_x86.exe`.

**Comment by armyc84** [comment]
> There is. However the new workflow got some minor flaws so 32 Bit didn't get build this time. But will add it manually (maybe today or later). Do note tho that I will name the 32 Bit version `youtube-dlc_x86.exe`.

Thank you for letting me know. I’ll be on the lookout for it! 😁

**Comment by blackjack4494** [comment]
@armyc84 Sorry forgot to ping you. The 32 Bit version got added.

**Comment by armyc84** [comment]
> @armyc84 Sorry forgot to ping you. The 32 Bit version got added.

Awesome, brotha! Thanks!
