### ISSUE TITLE
[hotstar] download not working since 20th september 403 forbidden error- [Broken]

### ISSUE THREAD

**Issue by crazy4cricket2807** [blackjack4494/youtube-dlc#145]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.09.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

<!--
Provide the complete verbose output of youtube-dlc that clearly demonstrates the problem.
Add the `-v` flag to your command line you run youtube-dlc with (`youtube-dlc -v <your command line>`), copy the WHOLE output and insert it below. It should look similar to this:
```
```

```
PASTE VERBOSE LOG HERE
-->
`youtube-dlc https://www.hotstar.com/in/sports/cricket/indian-premier-league/kolkata-knight-riders-vs-mumbai-indians-m701655/match-clips/replay-kkr-vs-mi-match-5/1540002194`
`[hotstar] 1540002194: Downloading webpage`
`[hotstar] 1540002194: Downloading token`
`ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HT
TPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.`
This happened when i tried to download using an tg-bot that uses the same url.
Cannot download this.
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by );

## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

so i was trying to download videos from hotstar, which were not drm protected it worked fine for a while but now whenever i use yt-dlc it just shows me 403 forbidden error or unable to download json data. kindly look into this.

**Comment by sumit-1988** [comment]
same here

**Comment by blackjack4494** [comment]
It used to work however I cannot debug it since I have no vpn currently.

**Comment by crazy4cricket2807** [comment]
> It used to work however I cannot debug it since I have no vpn currently.

mate can you try setup vpn extension for chrome and check for it as well and try to debug then.

here is the link 
https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp

**Comment by Ashish0804** [comment]
> It used to work however I cannot debug it since I have no vpn currently.

I'll email u one.

**Comment by blackjack4494** [comment]
I know that the `x-hs-usertoken` is needed but the implemented way to get it by using `https://api.hotstar.com/in/aadhar/v2/web/in/user/guest-signup` is not working anymore.  
Maybe @FaArIsH can help out here since he made the PR https://github.com/ytdl-org/youtube-dl/pull/25443 where this new endpoint is used.

@crazy4cricket2807 browser vpn is not really helping here but @Ashish0804 provided me one :)

So the way to fix this issue is by figuring out how to get `x-hs-usertoken` again. Maybe currently used endpoint is still working but just requires different parameters now.

**Comment by blackjack4494** [comment]
So far so good
> PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://www.hotstar.com/in/movies/dil-bechara/1260036017/watch" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.hotstar.com/in/movies/dil-bechara/1260036017/watch', '-v', '-F']
[debug] Loading archive file None
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dlc version 2020.09.23-1
[debug] Git HEAD: 3a379e5e8
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[hotstar] 1260036017: Downloading webpage
[hotstar] 1260036017: Downloading token
play/v1/playback/content/1260036017
{'desired-config': 'audio_channel:stereo|dynamic_range:sdr|encryption:plain|ladder:tv|package:dash|resolution:hd|subs-tag:HotstarVIP|video_codec:vp9', 'device-id': '38db3387-ec5f-4cdf-a92a-b81c7a45c53b', 'os-name': 'Windows', 'os-version': '10'}
[hotstar] 1260036017: Downloading JSON metadata
{'message': "Playback URL's fetched successfully", 'additionalInfo': {}, 'data': {'contentId': '1260036017', 'requestedConfig': 'audio_channel:stereo;dynamic_range:sdr;encryption:plain;ladder:tv;package:dash;resolution:hd;subscription:HotstarVIP;video_codec:vp9', 'playBackSets': [{'tagsCombination': 'audio_channel:stereo;audio_codec:aac;container:fmp4;dynamic_range:sdr;encryption:plain;ladder:tv;package:dash;resolution:hd;subscription:HotstarVIP;video_codec:h264', 'playbackUrl': 'https://hses3.hotstar.com/videos/hotstarint/1260036017/ .... 'playbackCDNType': 'INTERNAL', 'tokenAlgorithm': 'AKAMAI-HMAC'}]
[hotstar] 1260036017: Downloading MPD manifest
[hotstar] 1260036017: Downloading MPD manifest
[hotstar] 1260036017: Downloading MPD manifest
[hotstar] 1260036017: Downloading m3u8 information
[hotstar] 1260036017: Downloading MPD manifest
...

Will download a test file to see if it can download them as well and not just get the manifestes.

**Comment by Ashish0804** [comment]
Thanks a lot

**Comment by blackjack4494** [comment]
Do note tho the video OP used won't work with fix since it won't even play it browser. The links point to something `live` so I suspect the links are dead. Some other sport clips seems to be using drm.

**Comment by crazy4cricket2807** [comment]
but mate the videos do play... i have personally tested them out in my browser and they work fine...

**Comment by blackjack4494** [comment]
The one you linked won't play for me no matter what VPN I use. Others seem to have drm.

You can try to open devtools and then watch network tab for video files or manifests/mpd.  
Would be interesting what url/server you get the video segments from.
