### ISSUE TITLE
Skip playlists from other channels

### ISSUE THREAD

**Issue by Taurus3ye** [blackjack4494/youtube-dlc#147]
How can i download all playlists of a channel **expect** the ones that don't have videos from the channel owner. For example skip "Liked Videos" playlist.

**Comment by blackjack4494** [comment]
@Taurus3ye good question. There is `--match-filter` which you could use tho I haven't used it myself yet.  
I believe you need to specify the uploader (don't think you can use wildcard on command line for that) like  
`--match-filter "uploader = 'Some Uploader'"`

However if you embed youtube-dlc into a python program you should be able to use the uploader as a variable like this
``` python
with youtube_dlc.YoutubeDL(ydlc_opts) as ydlc_uploader:
    meta = ydlc_uploader.extract_info(
        'some_fancy_link', download=False) 

print(meta['uploader'])

ydlc_opts_uploader = {
    'match_filter': 'uploader = ' + meta['uploader']
    }

with youtube_dlc.YoutubeDL(ydlc_opts_uploader) as ydlc:
    ydl.download(['some_fancy_link_and_more'])
```

**Comment by Taurus3ye** [comment]
@blackjack4494 Thx will try
