### ISSUE TITLE
[Broken] bandcamp.com (fix included)

### ISSUE THREAD

**Issue by dym-sh** [blackjack4494/youtube-dlc#148]
recent bandcamp break+fix:

https://github.com/ytdl-org/youtube-dl/pull/26684/files

**Comment by someziggyman** [comment]
Thank you for your hard work! Looks like this fixed individual track extractions, however it fails to download "playlists". Please give this link a try:
https://reefthelostcauze.bandcamp.com/album/fight-music-three-pack

**Comment by blackjack4494** [comment]
@someziggyman will try to look at it when I got time.  

related issue from youtube-dl
@boatsr
https://github.com/ytdl-org/youtube-dl/issues/26848

**Comment by boatsr** [comment]
thanks
    On Friday, October 9, 2020, 12:05:28 PM EDT, Tom-Oliver Heidel <notifications@github.com> wrote:  
 
 


@someziggyman will try to look at it when I got time.

related issue from youtube-dl
@boatsr
ytdl-org#26848

**Comment by Sharpieman20** [comment]
I'm also having this issue

**Comment by dym-sh** [comment]
tryed on https://thesecession.bandcamp.com/track/death-may-die

atm still getting "ERROR: No video formats found;..."

**Comment by dym-sh** [comment]
i have made wrapper some time ago, which can help with downloads of full albums and even discographies:
https://github.com/dym-sh/y

it scraps the page for all `/album/*` => `/track/*` links, and tries to download every available track in mp3-320 first, instead of regular mp3-128
