### ISSUE TITLE
[Broken] [viki] "No video formats found" on modern episodes and shows.

### ISSUE THREAD

**Issue by dude22072** [blackjack4494/youtube-dlc#156]
## Checklist
- [X ] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dlc version **2020.09.16**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://www.viki.com/videos/1169478v-idol-on-the-quiz-episode-1']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.23-2
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92558-ge695b0beba, ffprobe N-92558-ge695b0beba
[debug] Proxy map: {}
[viki] Logging in
[viki] 1169478v: Downloading video JSON
[viki] 1169478v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 819, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\viki.py", line 285, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1359, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description
Both https://www.viki.com/tv/37282c-idol-on-the-quiz and https://www.viki.com/tv/37130c-mom-has-an-affair give the error mentioned in the title. To try and debug the issue I tried downloading https://www.viki.com/tv/21497c-sbs-inkigayo and while the oldest episodes available work just fine the newest episodes also give the same error. I'm using a paid VikiPass Plus account.

**Comment by dude22072** [comment]
Additional info, it seems `x-viki-app-ver` is `4.0.53` when I use chrome's webdev tools to view the headers, which is different that what the extractor uses (`_APP_VERSION = '2.2.5.1428709186'`).

**Comment by blackjack4494** [comment]
Maybe @zackmark29 can help.  
This video is drm protected with microsoft readyplay.  
Therefore `streams.json` returning an empty array. I don't know if it's possible to circumvent the drm with any vpn/proxy.

**Comment by zackmark29** [comment]
> Maybe @zackmark29 can help.
> This video is drm protected with microsoft readyplay.
> Therefore `streams.json` returning an empty array. I don't know if it's possible to circumvent the drm with any vpn/proxy.

Yeah it's drm protected I  think because I tested in my tool and it can't find the streams as well
But I'll try to find out the solution right now.

![image](https://i.imgur.com/ilvmNaR.png)

**Comment by zackmark29** [comment]
I just check that the author is Kocowa. That's why it's really DRM protected. try to visit their website it's the same.
But on some videos, You can get access the streams with using vpn.

**Comment by blackjack4494** [comment]
So, no way to download the videos.
