### ISSUE TITLE
Same title problem with "--download-archive"

### ISSUE THREAD

**Issue by Taurus3ye** [blackjack4494/youtube-dlc#162]
It isn't possible to download multiple YT videos with the same title when the "--download-archive" command is used. It will write the Video-ID into the archive text file but skip downloading the second video.

example videos:
https://www.youtube.com/watch?v=6fC1-7OY6Gc
https://www.youtube.com/watch?v=93VzknCm7YM

**Comment by Casper-09** [comment]
use 
> --output "%(title)s - [%(id)s].%(ext)s"

**Comment by Taurus3ye** [comment]
> 
> 
> use
> 
> > --output "%(title)s - [%(id)s].%(ext)s"

ah ok thx
