### ISSUE TITLE
[Feature Request] Show the true version number

### ISSUE THREAD

**Issue by nicolaasjan** [blackjack4494/youtube-dlc#178]
- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dlc version **2020.10.09**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Youtube-dlc reports the wrong version;
`2020.09.29` instead of `2020.10.09`... ;)

`./youtube-dlc/youtube_dlc/version.py` needs to be changed.

**Comment by blackjack4494** [comment]
@nicolaasjan do you mean just the `version.py` or the program itself?  
I only test the pip version
> root@ffm1:~# youtube-dlc --version
2020.10.09

The `version.py` isn't updated automatically yet. Since I do versioning with a separate script in the workflow file (CI/CD pipeline)  
You can have a look at it if you are interested.  
https://github.com/blackjack4494/youtube-dlc/blob/master/.github/workflows/build.yml

**Comment by nicolaasjan** [comment]
> @nicolaasjan do you mean just the `version.py` or the program itself?
> I only test the pip version
> 
> > root@ffm1:~# youtube-dlc --version
> > 2020.10.09
> 
> The `version.py` isn't updated automatically yet. Since I do versioning with a separate script in the workflow file (CI/CD pipeline)
> You can have a look at it if you are interested.
> https://github.com/blackjack4494/youtube-dlc/blob/master/.github/workflows/build.yml

I meant the output of `youtube-dlc --version` was `2020.09.29` here...

**Comment by blackjack4494** [comment]
Ah okay thanks for letting me know. Will look into it. The pip and windows versions should be fine. So it's only the Linux version that needs a fix right?

**Comment by nicolaasjan** [comment]
> Ah okay thanks for letting me know. Will look into it. The pip and windows versions should be fine. So it's only the Linux version that needs a fix right?

My bad?

It was the version I compiled myself from the master tree, that was showing the wrong version...
Just tested the one available for download and that showed the correct version.
```
nico@nico-desktop:~$ youtube-dlc --version
2020.10.09
```
Maybe close this issue now?
