### ISSUE TITLE
[Broken] Southpark.de and all MTVN related Sites now use a ComedyCentral-like structure and therefore have broken extractors

### ISSUE THREAD

**Issue by okh-mzny** [blackjack4494/youtube-dlc#187]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.09.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
A:\>youtube-dlc -v https://www.southpark.de/folgen/4xxqgo/south-park-coole-kuehe-staffel-2-ep-13
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.southpark.de/folgen/4xxqgo/south-park-coole-kuehe-staffel-2-ep-13']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.29
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-07-13-7772666, ffprobe git-2020-07-13-7772666
[debug] Proxy map: {}
[generic] south-park-coole-kuehe-staffel-2-ep-13: Requesting header
WARNING: Falling back on generic information extractor.
[generic] south-park-coole-kuehe-staffel-2-ep-13: Downloading webpage
[generic] south-park-coole-kuehe-staffel-2-ep-13: Extracting information
ERROR: Unsupported URL: https://www.southpark.de/folgen/4xxqgo/south-park-coole-kuehe-staffel-2-ep-13
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\generic.py", line 3382, in _real_extract
youtube_dlc.utils.UnsupportedError: Unsupported URL: https://www.southpark.de/folgen/4xxqgo/south-park-coole-kuehe-staffel-2-ep-13
```

## Description

https://github.com/ytdl-org/youtube-dl/issues/26841 
and 
https://github.com/ytdl-org/youtube-dl/issues/26763 
are applicable here.

Recently every MTVN related site has changed its site structure, and so have all Southparkstudios sites.
As mentioned in youtube-dl#26763 the ComedyCentral extractor needs to be used in order to properly extract. This should be trivial so I hope someone can look at it.

Thank you :)

**Comment by blackjack4494** [comment]
Some (mtvn like southpark) sites have a dedicated extractor but using MTV extractor as base. The new mgid extraction is already implemented as a new function.  
It should be very straight forward to patch it.

**Comment by blackjack4494** [comment]
@okh-mzny a patch for southpark.de is done.  
I cannot test the other sites as they are redirecting me to the german page so I would need vpn to fix the other sites if they aren't working which I assume.
https://github.com/blackjack4494/youtube-dlc/pull/188

**Comment by blackjack4494** [comment]
For future reference:
`https://www.southpark.de/api/context/mgid%3Aarc%3Aseason%3Asouthpark.intl%3A25eebaaa-ed8e-11e0-aca6-0026b9414f30/episode/0/1/ascending` 
this api can be used to retrieve all episodes of a season
