### ISSUE TITLE
[Question] where does youtube-dlc look for youtube-dl.conf

### ISSUE THREAD

**Issue by sdsucks** [blackjack4494/youtube-dlc#194]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

youtube-dlc doesn't apply those options in c:\Users\MyName\youtube-dl.conf.
manually adding the options in the command line works just fine, of course.

**Comment by blackjack4494** [comment]
If you don't specify `--config-location` to use your `youtube-dl.conf` it will use `youtube-dlc.conf` by default.
