### ISSUE TITLE
[Question] How to get/show direct download link with chosen format

### ISSUE THREAD

**Issue by quyleanh** [blackjack4494/youtube-dlc#207]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I get/show direct download link with chosen format?

For example, if I use `-F` flag for showing all available formats

```
$ youtube-dlc -F https://www.facebook.com/honganhaoethaibinh/videos/360047792009932/
[facebook] 360047792009932: Downloading webpage
[facebook] 360047792009932: Downloading webpage
[facebook] 360047792009932: Downloading webpage
[info] Available formats for 360047792009932:
format code        extension  resolution note
2027693547365426a  m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.5 (48000Hz)
382022583207050v   mp4        256x144    DASH video   95k , mp4_dash container, avc1.64000C, video only
2778615029127443v  mp4        426x240    DASH video  231k , mp4_dash container, avc1.640015, video only
348238873165100v   mp4        640x360    DASH video  452k , mp4_dash container, avc1.64001E, video only
891567584710964v   mp4        854x480    DASH video  824k , mp4_dash container, avc1.64001F, video only
841507080009330v   mp4        1280x720   DASH video 1574k , mp4_dash container, avc1.640020, video only
1060163121084435v  mp4        1920x1080  DASH video 2659k , mp4_dash container, avc1.640032, video only
dash_sd_src        mp4        unknown    (best)
```

then I want to download and show direct link for `1060163121084435v` video and `2027693547365426a` audio. How can I get this direct link?

Thank you.

**Comment by quyleanh** [comment]
Sorry. I have figured out. There is option `-g` to show direct link.
Close this issue.

**Comment by blackjack4494** [comment]
Facebook videos work? I thought some people mentioned it is broken 😕

**Comment by quyleanh** [comment]
@blackjack4494 it works well. I haven't tested full yet, but the public fan page video link is fine.
