### ISSUE TITLE
[Feature Request] README.md Update (aria2c alongside wget)

### ISSUE THREAD

**Issue by TheYellowArchitect** [blackjack4494/youtube-dlc#220]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dlc version **2020.09.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

On the Installation, it says using wget and curl
However, aria2c is as good as wget, if not better.
So, for those who downloaded aria2c instead of wget (dependency bloat), and have only aria2c, would benefit from this edit
Below "using curl", "using wget", there should also be "using aria2c"
```
sudo aria2c --dir=/usr/local/bin/youtube-dlc https://github.com/blackjack4494/youtube-dlc/releases/latest/download/youtube-dlc
sudo chmod a+rx /usr/local/bin/youtube-dlc
```

I tried to do a fork via Github, so as to push, but for some reason it forks youtube-dl instead
Anyhow, it's a minor edit, hope someone can do it for me

**Comment by pukkandan** [comment]
youtube-dlc repo is moved to https://github.com/blackjack4494/yt-dlc after the DMCA takedown. However, it has also had no updates in over 2 months. You can use my fork [yt-dlp](https://github.com/pukkandan/yt-dlp) instead if you want

**Comment by TheYellowArchitect** [comment]
ah lel, yt-dlc was supposed to replace youtube-dl since its development had slowed down considerably

looking at the [differences](https://github.com/pukkandan/yt-dlp#new-features), it seems to be exactly what I expected of youtube-dlc, aka a concentration of all youtube-dl, I'm moving there, thank you :)

**Comment by pukkandan** [comment]
I am focused more on implementing features/fixes that people who use my fork actually want to get fixed. I am maintaining the fork solo in my free time, so I have no time to scour through youtube-dl issues and try to fix them all. So if you want something fixed, make sure you open an issue or even better, a PR
