### ISSUE TITLE
Twitch URL structure

### ISSUE THREAD

**Issue by ahmedtds** [blackjack4494/youtube-dlc#32]
First, thanks for this initiative

Can you merge one of these PRs please?
https://github.com/ytdl-org/youtube-dl/pull/25010
https://github.com/ytdl-org/youtube-dl/pull/21812

They aim to solve same issue, since the previous one (21812) were never merged for more than a year, there was a new PR by someone else (25010) but that's not merged for months as well

Thanks

**Comment by ahmedtds** [comment]
These were relevant issues:
https://github.com/ytdl-org/youtube-dl/issues/24263
https://github.com/ytdl-org/youtube-dl/issues/21811

Both issues are for same problem, one of them should have been closed as duplicate

**Comment by blackjack4494** [comment]
@ahmedtds sure will have a look.
I already merged some twitch related PR https://github.com/blackjack4494/youtube-dlc/pull/8
which fixes new api call

pre patch
> theidel@DESKTOP-S2JEM09:/mnt/c/Users/Tom-Oliver Heidel$ youtube-dl http://www.twitch.tv/vanillatv/profile -F
[twitch:profile] vanillatv: Downloading channel info JSON
ERROR: twitch:profile returned error: Bad Request - Channel identifier "vanillatv" is in an invalid format

patched
> theidel@DESKTOP-S2JEM09:/mnt/c/Users/Tom-Oliver Heidel$ youtube-dlc http://www.twitch.tv/vanillatv/profile -F
[twitch:profile] vanillatv: Downloading channel info JSON
[twitch:profile] 22744919: Downloading profile JSON page 1
[twitch:profile] 22744919: Downloading profile JSON page 2
[twitch:profile] 22744919: Downloading profile JSON page 3
[twitch:profile] 22744919: Downloading profile JSON page 4
[twitch:profile] 22744919: Downloading profile JSON page 5
[twitch:profile] 22744919: Downloading profile JSON page 6
[download] Downloading playlist: VanillaTV
[twitch:profile] playlist VanillaTV: Collected 412 video ids (downloading 412 of them)
[download] Downloading video 1 of 412
[twitch:vod] 49155755: Downloading vod info JSON
[twitch:vod] 49155755: Downloading vod access token
[twitch:vod] 49155755: Downloading m3u8 information
[info] Available formats for v49155755:
format code  extension  resolution note
Audio_Only   mp4        audio only 3800k , mp4a.40.2
Source       mp4        1280x720   3800k , avc1.4D4029, mp4a.40.2 (best)
[download] Downloading video 2 of 412

will have a look at those other ones. But seems they will work :)

**Comment by blackjack4494** [comment]
@ahmedtds got merged with https://github.com/blackjack4494/youtube-dlc/pull/34
will be released within the next few minutes.

**Comment by ahmedtds** [comment]
@blackjack4494 Thank you so much, tried it, works great.

I want to ask feedback of @vxbinaca as well because of this:

Now after this fix new twitch urls like `https://www.twitch.tv/x/videos?filter=archives&sort=time` works correctly but old structure like `https://twitch.tv/x/videos/past-broadcasts` doesn't work anymore. It's not possible to get an URL like `"videos/past-broadcasts"` from twitch website anymore so it should be OK but wanted to ask @vxbinaca if it does break any of their scripts? Can you comment on this? Maybe you have scripts that passes URL like `https://twitch.tv/x/videos/past-broadcasts` I don't know. Just wanted to make sure my PR request didn't cause any malfunction.

**Comment by vxbinaca** [comment]
> @blackjack4494 Thank you so much, tried it, works great.
> 
> I want to ask feedback of @vxbinaca as well because of this:
> 
> Now after this fix new twitch urls like `https://www.twitch.tv/x/videos?filter=archives&sort=time` works correctly but old structure like `https://twitch.tv/x/videos/past-broadcasts` doesn't work anymore. It's not possible to get an URL like `"videos/past-broadcasts"` from twitch website anymore so it should be OK but wanted to ask @vxbinaca if it does break any of their scripts? Can you comment on this? Maybe you have scripts that passes URL like `https://twitch.tv/x/videos/past-broadcasts` I don't know. Just wanted to make sure my PR merge request didn't cause any malfunction.

Firstly, thank you for tagging me.

So I can test this once we adapt [my tool that mirrors videos](https://github.com/bibanon/tubeup/) and repoint it's library calls to this script instead of YTDL. Thats easy one of the other guys who maintain it can do that I might even be able to do it even though I'm not a programmer. As long as the maintainers don't stray too far from YTDL library calls I should be good.

What the issue I have is my ripping batch files are channel based, so when channels in a site stop working it's not a good thing. 

Pending a library call switch and string replacing URLs in my batch files I'm calling this one fixed. If channels extract I'm good thats all I need the other issues are surrmountable.

**Comment by blackjack4494** [comment]
I noticed there are more filters  
`featured`  
`clips` but got `clips` as endpoint and not `videos`  
`collections`  
`past_premieres`  

Also I tried some endpoints on live streaming users. Problem here is that twitch adds the live stream to the videos (in some categories like `featured`). So archiving someone who is streaming live will be an issue depending on the endpoint. There would be some workaround that you could check first if the streamer is online and streaming so you would skip the first video in those categories where the live stream is added.

I randomly clicked on some streamer just to showcase  
![image](https://user-images.githubusercontent.com/4406639/92310213-72f08480-efac-11ea-8d95-ec77b7fa76ef.png)

But the weird part is that this won't happen on every streamer. Another bug is that it sometimes just shows one video and won't look for more.

**Comment by vxbinaca** [comment]
> I noticed there are more filters
> `featured`
> `clips` but got `clips` as endpoint and not `videos`
> `collections`
> `past_premieres`
> 
> Also I tried some endpoints on live streaming users. Problem here is that twitch adds the live stream to the videos (in some categories like `featured`). So archiving someone who is streaming live will be an issue depending on the endpoint. There would be some workaround that you could check first if the streamer is online and streaming so you would skip the first video in those categories where the live stream is added.
> 
> I randomly clicked on some streamer just to showcase
> ![image](https://user-images.githubusercontent.com/4406639/92310213-72f08480-efac-11ea-8d95-ec77b7fa76ef.png)
> 
> But the weird part is that this won't happen on every streamer. Another bug is that it sometimes just shows one video and won't look for more.

The solution is to use the 'check if life' flag who's proper name escapes me right now. It will skip that live broadcast. This is default with extractors like YouTube but not Twitch. We want to implement that flag into Tubeup.
