### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by DesweR** [blackjack4494/youtube-dlc#40]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello! Thank you so much for this fork!
Could you add support for Windows XP? This is still needed...

**Comment by DesweR** [comment]
I was able to make a build for Windows XP.
I used:
Python 3.4.4
PyInstaller 3.5

>May I ask why support for XP is still needed?

I am using youtube-dlc for a PotPlayer plugin.
PotPlayer still has users on Windows XP.

>Furthermore is 32 or 64 Bit needed?

x86, like the original youtube-dl.

I would also like youtube-dlc to have version information in resources.

Thank you in advance for your help!

**Comment by DesweR** [comment]
I was able to make a build for Windows XP.
I used:
Python 3.4.4
PyInstaller 3.5

>May I ask why support for XP is still needed?

I am using youtube-dlc for a PotPlayer plugin.
PotPlayer still has users on Windows XP.

>Furthermore is 32 or 64 Bit needed?

x86, like the original youtube-dl.

I would also like youtube-dlc to have version information in resources.

Thank you in advance for your help!

**Comment by blackjack4494** [comment]
> I would also like youtube-dlc to have version information in resources.

Sure can be added. Just had a look into pyinstaller docs. Will try to include XP supported binary in the next release. But will let you know @DesweR so that you can have a try first. Will try my best to add support for it but won't install any XP environment to test functionality. Hope you can understand :)

**Comment by DesweR** [comment]
Thanks!

>I assume your Python 3.4.4 was a 32 Bit installation then?
Yes

**Comment by nicolaasjan** [comment]
>Will try my best to add support for it but won't install any XP environment to test functionality.

I can test as well, as I have a Windows XP (32bit) virtual machine here :)

**Comment by blackjack4494** [comment]
I am trying to set up a (github) action that will automatically build the exe using pyinstaller with an older 32 bit python. That should also slim down the size as I am not using any virtual environment (python - not talking about a virtual machine) so the size is quite big right now ~13mb. Should come down to 5-7mb if compiled in an isolated environment.

**Comment by nicolaasjan** [comment]
> I was able to make a build for Windows XP.
> I used:
> Python 3.4.4
> PyInstaller 3.5

Did you build it on XP itself?
I just tried to install Python 3.4.4 and PyInstaller 3.5, but PyInstaller threw me an error at the end...:


```
Installed c:\python34\lib\site-packages\pyinstaller-3.5-py3.4.egg
Processing dependencies for PyInstaller==3.5
Searching for pefile>=2017.8.1
Reading https://pypi.python.org/simple/pefile/
Best match: pefile 2019.4.18
Downloading https://files.pythonhosted.org/packages/36/58/acf7f35859d541985f0a6e
a3c34baaefbfaee23642cf11e85fe36453ae77/pefile-2019.4.18.tar.gz#sha256=a5d6e8305c
6b210849b47a6174ddf9c452b2888340b8177874b862ba6c207645
error: Download error for https://files.pythonhosted.org/packages/36/58/acf7f358
59d541985f0a6ea3c34baaefbfaee23642cf11e85fe36453ae77/pefile-2019.4.18.tar.gz#sha
256=a5d6e8305c6b210849b47a6174ddf9c452b2888340b8177874b862ba6c207645: [SSL: CERT
IFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by blackjack4494** [comment]
Well I gave it a try to build youtube-dlc with python 3.4.2 and pyinstaller 3.5

This is what I produced [youtube-dlc.exe](http://locoserver.net/dl/youtube-dlc.exe) running latest release version 2020.09.12

Give me some feedback @DesweR and @nicolaasjan will add it to latest release then.

**Comment by nicolaasjan** [comment]
> 
> 
> Well I gave it a try to build youtube-dlc with python 3.4.2 and pyinstaller 3.5
> 
> This is what I produced [youtube-dlc.exe](http://locoserver.net/dl/youtube-dlc.exe) running latest release version 2020.09.12
> 
> Give me some feedback @DesweR and @nicolaasjan will add it to latest release then.

I will test some things when I get back home again (few days) :)

Why python 3.4.2 (3.4.4 is the latest version working on XP)?

**Comment by blackjack4494** [comment]
> Why python 3.4.2 (3.4.4 is the latest version working on XP)?

I didn't use XP but just compiled it on Win10. However I had troubles using 3.4.4 and PyInstaller - some SSL related issues. I read somewhere that there was some issue around that version so I just used a version which was a bit older. But that shouldn't negatively impact anything.

Looking forward for your feedback :)  
Enjoy your time whatever you are doing.

**Comment by ochompsky** [comment]
why even bother to spend a minute of development time for XP support?

no need to cater to people too dumb to update to a supported OS.

**Comment by nicolaasjan** [comment]
> 
> Looking forward for your feedback :)
> Enjoy your time whatever you are doing.

Hi, I'm back!

I've tested some different scenarios with youtube-dlc (32bit) on Windows XP.
For the most part it **just works**®, but of course you'll need a 32bit XP-compatible ffmpeg and ffprobe version.
I always get it from [here](https://rwijnsma.home.xs4all.nl/files/ffmpeg/?C=M;O=D).

One thing that isn't  possible however, is thumbnail embedding in mp4/m4a files, because the developer of AtomicParsley is not providing a 32bit version...
See this [issue](https://github.com/wez/atomicparsley/issues/6).
Not really a showstopper, IMHO.

**Comment by DesweR** [comment]
> Give me some feedback @DesweR and @nicolaasjan will add it to latest release then.

It's all right!
The only thing is the version information is inverted (2020.9.6.0 - 6.9.2020.0)

**Comment by blackjack4494** [comment]
> > Give me some feedback @DesweR and @nicolaasjan will add it to latest release then.
> 
> It's all right!
> The only thing is the version information is inverted (2020.9.6.0 - 6.9.2020.0)

Yeah that's because I live in Germany/Europe and dates look different. The one youtube-dl uses is us version. But I want to switch to regular versioning soon anyway.

**Comment by DesweR** [comment]
> The one youtube-dl uses is us version. But I want to switch to regular versioning soon anyway.

It's a pity, the versions like youtube-dl were convenient.

**Comment by blackjack4494** [comment]
There will be an automated 32 bit build when the workflow update is pushed. But it needs some minor tweaking before I update it and still having unstable internet.

**Comment by nicolaasjan** [comment]
Just built the 32bit build for Windows XP, but I noticed it shows the wrong version when you hover over it in Explorer...

![version](https://user-images.githubusercontent.com/14093220/94053887-2cd45700-fddb-11ea-83c7-045f8ef0b2f6.png)

CMD output:

```
Microsoft Windows XP [versie 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\WINDOWS\system32>youtube-dlc --version
2020.09.23-1

C:\WINDOWS\system32>
```
And shouldn't it show 2020.09.23-2 in CMD?

**Comment by blackjack4494** [comment]
Haven't actually updated the `ver.txt` or the description how to build the exe now.
I embedded the build process into a python file `pyinst.py` for easier automated builds. However I will likely keep support for building with `make_win.bat` or even write a simple PowerShell script in addition.
To automate self updating `ver.txt` you would need a template so the version is a variable placeholder which then will be overwritten by newest version.

**Comment by nicolaasjan** [comment]
> Haven't actually updated the `ver.txt` or the description how to build the exe now.
> I embedded the build process into a python file `pyinst.py` for easier automated builds. However I will likely keep support for building with `make_win.bat` or even write a simple PowerShell script in addition.
> To automate self updating `ver.txt` you would need a template so the version is a variable placeholder which then will be overwritten by newest version.
> You could run `pyinst.py` with 32 Bit version of python. However I advise to use `pyinst32.py` for this.

Thanks!
`pyinst32.py` works:

![proof](https://user-images.githubusercontent.com/14093220/94115234-b7ec3600-fe49-11ea-9076-fcd2f2e21940.png)

Had to rename youtube-dlc_x86.exe to youtube-dlc.exe though.

CMD still thinks it's version 2020.09.23-1...

**Comment by blackjack4494** [comment]
> > Haven't actually updated the `ver.txt` or the description how to build the exe now.
> > I embedded the build process into a python file `pyinst.py` for easier automated builds. However I will likely keep support for building with `make_win.bat` or even write a simple PowerShell script in addition.
> > To automate self updating `ver.txt` you would need a template so the version is a variable placeholder which then will be overwritten by newest version.
> > You could run `pyinst.py` with 32 Bit version of python. However I advise to use `pyinst32.py` for this.
> 
> Thanks!
> `pyinst32.py` works:
> 
> ![proof](https://user-images.githubusercontent.com/14093220/94115234-b7ec3600-fe49-11ea-9076-fcd2f2e21940.png)
> 
> Had to rename youtube-dlc_x86.exe to youtube-dlc.exe though.
> 
> CMD still thinks it's version 2020.09.23-1...

You mean when you type `youtube-dlc --version`? Maybe I have forgot to update `version.py` then.

**Comment by nicolaasjan** [comment]
> 
> You mean when you type `youtube-dlc --version`? Maybe I have forgot to update `version.py` then.

Yes, I meant the output of `youtube-dlc --version`, sorry.
`version.py` is indeed still at `2020.09.23-1`
