### ISSUE TITLE
Automate all releases

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/youtube-dlc#41]
Current situation:  
python publish, a github workflow (actions), is triggered when there is a push (result of merging a PR) on releases branch. 

However it would come in handy to also automate the release of (1) Unix and (2) Windows Binaries (including a 32 Bit version aimed to support (3) XP).
(4) Therefore an automatic version update process is required.

Solutions would be to extend current workflow script which I would advise against but rather add one or more.

As a side note:
tweak `pyinstaller` to include extended informations like versioning and reduce exe size by excluding unnecessary packages. first step would be to use a virtual environment then install all requirements and finally compile it. The build folder can be inspected to see if there is room for more improvement resulting in smaller exe by analyzing and inspecting the generated files by `pyinstaller` and further tweaking of the `spec` file. In the end `pyinstaller` script should point and compile the `spec` file and not the `__main__.py`

**Comment by davralin** [comment]
Also, autobuild/publish a docker container?

Because why the hell not.

**Comment by blackjack4494** [comment]
Yes. I almost finished the new workflow file. Just need to tweak some minor points and check it before updating it.  
It will build all binaries (including 32 bit for windows) and update the issue templates on each release.

@davralin what docker container have you thought about?

**Comment by blackjack4494** [comment]
New workflow is active. It's working somehow but still a mess.
