### ISSUE TITLE
[viki] wrongly timed subtitles + more (api)

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/youtube-dlc#43]
Some videos may have wrongly timed subtitles but not all.

I already pointed out a solution to this by adding `stream_id` to the query which will download the correctly timed subtitles
https://github.com/ytdl-org/youtube-dl/issues/26385

**Comment by zackmark29** [comment]
Actually I already found out that you can use any stream_id and it will still work and give you the correct subtitle
like this stream_id=**95084494**: 

and must generate signature.

Result:
https://api.viki.io/v4/videos/1119423v/subtitles/en.srt?stream_id=95084494&app=100005a&t=1599514353&site=www.viki.com&sig=3a14172eb32d8444eda9c0e89003c3d026c38a62

**Comment by blackjack4494** [comment]
We should take advantage of this api `https://www.viki.com/api/` as well since it returns other (more) data than `https://api.viki.io`.

Base request
```
curl 'https://www.viki.com/api/videos/91001v' \
-H 'x-viki-app-ver: 4.0.53' \
--compressed
```

**Comment by zackmark29** [comment]
> We should take advantage of this api `https://www.viki.com/api/` as well since it returns other (more) data than `https://api.viki.io`.
> 
> Base request
> 
> ```
> curl 'https://www.viki.com/api/videos/91001v' \
> -H 'x-viki-app-ver: 4.0.53' \
> --compressed
> ```

Yeah, that's what I'm using as well.

**Comment by blackjack4494** [comment]
Yup so far I only use v4 endpoint.  
You can check the code to see how I added the `stream_id` :)

Will close this issue for now as it's resolved by https://github.com/blackjack4494/youtube-dlc/pull/69

Let me know if there is anything I missed.
