### ISSUE TITLE
Cant use outtmpl on some age restricted videos?

### ISSUE THREAD

**Issue by FlyingThunder** [blackjack4494/youtube-dlc#45]
- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.07.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

```
[youtube] 5EA21Gt533Q: Downloading webpage
[youtube] 5EA21Gt533Q: Downloading embed webpage
[youtube] 5EA21Gt533Q: Refetching age-gated info webpage
[download] Destination: test.mp3
[download] 100% of 3.41MiB in 00:00                  
[ffmpeg] Post-process file test.mp3 exists, skipping
```

Hello, the age restriction skipper works well for videos, however when i use the "outtmpl" option that works fine for non-restricted videos, it gives me a broken mp3 for certain age-restricted videos. this is the code, and video, im running:

`import youtube_dlc

url = "https://www.youtube.com/watch?v=5EA21Gt533Q"    #age restricted, outputs a broken mp3
url2 = "https://www.youtube.com/watch?v=v6Ln5kWRqVg"  #non age restricted
url3 = "https://www.youtube.com/watch?v=9hloj2gVU04"    #also age restricted, but works?
url4 = "https://www.youtube.com/watch?v=rYpS09ySaPY"    #also age restricted but doesnt work

ydl_opts = {
    'outtmpl': 'test.mp3',
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
}
with youtube_dlc.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])`

the output of this is an mp3 file that VLC does not play, it just opens and nothing happens. everything else works fine.
i am very confused why some videos wont give me an mp3 like it should - maybe its related to the length?

**Comment by blackjack4494** [comment]
```
import youtube_dlc

url = "https://www.youtube.com/watch?v=5EA21Gt533Q" #age restricted, outputs a broken mp3
url2 = "https://www.youtube.com/watch?v=v6Ln5kWRqVg" #non age restricted
url3 = "https://www.youtube.com/watch?v=9hloj2gVU04" #also age restricted, but works?
url4 = "https://www.youtube.com/watch?v=rYpS09ySaPY" #also age restricted but doesnt work

ydl_opts = {
  'outtmpl': '%(title)s-%(id)s.%(ext)s',
  'format': 'bestaudio/best',
  'postprocessors': [{
  'key': 'FFmpegExtractAudio',
  'preferredcodec': 'mp3',
  'preferredquality': '192',
  }],
}

with youtube_dlc.YoutubeDL(ydl_opts) as ydl:
  [ydl.download([i]) for i in [url, url2, url3, url4]]
```

Tested with Python 3.5.2 and ffmpeg version 2.8.17-0ubuntu0.1 under  WSL (Ubuntu16.04)  
Everything works for me. Maybe your ffmpeg version or VLC is not working properly?

**Comment by FlyingThunder** [comment]
ah yea it was ffmpeg, i didnt have the exe in the folder but i didnt notice because some mp3s somehow worked fine anyways.... sorry and thanks

**Comment by blackjack4494** [comment]
No problem. Glad I could help :)
