### ISSUE TITLE
Change in xhamster.py needed?

### ISSUE THREAD

**Issue by nicolaasjan** [blackjack4494/youtube-dlc#51]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dlc version **2020.09.06**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

The main youtube-dl project has changed [line 141](https://github.com/ytdl-org/youtube-dl/blob/d51e23d9fc709a80ca037199a46e59c729a1192e/youtube_dl/extractor/xhamster.py#L141) to:
```
(r'window\.initials\s*=\s*({.+?})\s*;\s*</script>',
r'window\.initials\s*=\s*({.+?})\s*;'), webpage, 'initials',
```
Is it necessary to change the corresponding [line 141](https://github.com/blackjack4494/youtube-dlc/blob/2045de7c32035aa830b16e35a056a769aa7596be/youtube_dlc/extractor/xhamster.py#L141) here as well?
Now:
```
r'window\.initials\s*=\s*({.+?})\s*;', webpage, 'initials',
```

**Comment by blackjack4494** [comment]
will be merging updated youtube-dl's master branch.
https://github.com/blackjack4494/youtube-dlc/pull/52

But before that I will check the changes. It's good to see some activity going on again. Tho this recent update is fixing youtube, twitch and adult extractor mainly. Will try to stay in line with youtube-dl's master branch but in addition include PRs that haven't been merged or simply dropped. Also will try to merge fixes more active (meaning faster compared to main project).  
:)

**Comment by blackjack4494** [comment]
@nicolaasjan merged the latest update of youtube-dl so the requested fix should be included. However I did not test it myself (trusting youtube-dl here)
