### ISSUE TITLE
[ndr/daserste] 

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/youtube-dlc#67]
https://github.com/ytdl-org/youtube-dl/issues/26563

[branch daserste-ndr](https://github.com/blackjack4494/youtube-dlc/tree/daserste-ndr)
fix will be merged soon.

**Comment by blackjack4494** [comment]
@FelixBer

Well, what can I say. I forgot to merge it into latest release. But will do in next release.

**Comment by FelixBer** [comment]
Thanks :)

**Comment by blackjack4494** [comment]
https://github.com/blackjack4494/youtube-dlc/pull/95
