### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by varbhat** [blackjack4494/youtube-dlc#76]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

youtube-dlc can download video/audio from more sites other than YouTube. This would be very good time to rename the project to indicate so.

**Comment by varbhat** [comment]
@blackjack4494  any reply ?

**Comment by blackjack4494** [comment]
Yes I feel you.  
The reason why I kept the name youtube-dl and added a 'c' to it is that you can easily merge it back (folder will be auto identified as renamed). If youtube-dl ever want to merge something from this fork whatsoever.

But you are totally right. Some neutral name would be better.

**Comment by varbhat** [comment]
I think that they could have banned you because they think that your fork might be better and might split up userbase and their userbase might decrease.

Because of your ban,i don't think that they are interested in your fork/interested in getting merges from this project. 

I personally think that this project could be named to somewhat more intuitive. This could also increase the popularity of this project.

**Comment by varbhat** [comment]
I am closing this issue as you have answered my question ( I assume "NO" as answer)

**Comment by blackjack4494** [comment]
I created a label called Future so it's easier to sort for those.
But feel free to let this open and discuss about it. I just stated my opinion but is only for you to understand why I did it.
This should be community based/centered so in no means do I want to dictate anything and am glad about hearing other people's opinions and solutions to this :)

**Comment by varbhat** [comment]
Ok, if you were to consider renaming, please consider my proposals:

1) mget -> media-get (pun on wget)

2) vidget -> video-get

3) mfetch -> media fetch

4) mdl -> media dl
