### ISSUE TITLE
release 2020.09.12 mis-titled on Releases page

### ISSUE THREAD

**Issue by ploxiln** [blackjack4494/youtube-dlc#83]
The 2020.09.12 release is titled "2020.09.06", same as the previous release:

<img width="648" alt="Screen Shot 2020-09-12 at 10 45 54 AM" src="https://user-images.githubusercontent.com/649835/92998019-6c4e9980-f4e5-11ea-9603-669722555279.png">

this was a bit confusing initially

**Comment by blackjack4494** [comment]
![image](https://user-images.githubusercontent.com/4406639/93009513-8094a400-f582-11ea-9c7a-97814c696f3b.png)

Fixed it. Thanks for mentioning it.
