### ISSUE TITLE
Implement a flag to be able to trim long filenames to a number or characters especified by user.

### ISSUE THREAD

**Issue by ErikEBZ** [blackjack4494/youtube-dlc#85]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Sometimes when downloading for example videos of twitter, youtube-dl downloads the video using the tweet text as title for the video. That's ok, but when the tweet is long, youtube-dl launch an error like "Impossible to download - Filename too long."

A flag to cut the file name to for example the first 100 characters would be really useful.

I would suggest a flag like: 

**--trim-file-name MAX_CHARACTER_NUMBER**

So when it is specified by user, the filename gets cut until filename reach the MAX_CHARACTER_NUMBER.

**Comment by 0xFlugel** [comment]
An alternative would be to catch this particular error and retry with an automatically shortened filename until it either works or fails because the path already exists.

**Comment by blackjack4494** [comment]
Should be quite simple to implement a check. This shouldn't be needed in first place. I would blame it on the one who did the Twitter extractor to havent thought about this 😅
I have to see whether this can be done globally without modifications needed on the extractors itself or whether it's required that each extractor has to use a function to check filename and correct it accordingly.

**Comment by blackjack4494** [comment]
@ErikEBZ you asked for it. So here it will come https://github.com/blackjack4494/youtube-dlc/commit/bdc3fd2f35c67c513dfc2843d5168f905d7bd5c8

>PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://music.youtube.com/watch?v=tke6Gk4VXaI" --trim-file-name 5
[youtube] tke6Gk4VXaI: Downloading webpage
[download] 100% of 28.73MiB in 00:02
[download] Destination: My Bo.f251.webm
[download] 100% of 6.70MiB in 00:00
[ffmpeg] Merging formats into "My Bo.webm"
Deleting original file My Bo.f248.webm (pass -k to keep)
Deleting original file My Bo.f251.webm (pass -k to keep)

>PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://music.youtube.com/watch?v=tke6Gk4VXaI"
[youtube] tke6Gk4VXaI: Downloading webpage
[download] Destination: My Boy (Meduza Remix)-tke6Gk4VXaI.f248.webm
[download] 100% of 28.73MiB in 00:02
[download] Destination: My Boy (Meduza Remix)-tke6Gk4VXaI.f251.webm
[download] 100% of 6.70MiB in 00:00
[ffmpeg] Merging formats into "My Boy (Meduza Remix)-tke6Gk4VXaI.webm"
Deleting original file My Boy (Meduza Remix)-tke6Gk4VXaI.f251.webm (pass -k to keep)
Deleting original file My Boy (Meduza Remix)-tke6Gk4VXaI.f248.webm (pass -k to keep)

Will be shipped in next release which should come later this day.

**Comment by GentleRock** [comment]
The issue needs to be reopened as the committed change

```
      if trim_file_name:
          no_ext, *ext = filename.rsplit('.', 2)
          filename = join_nonempty(no_ext[:trim_file_name], *ext, delim='.')
```
has a bug in it.

The parameter 2 should be changed into 1, that is 
```
          no_ext, *ext = filename.rsplit('.', 1)
```
otherwise it wouldn't work as soon as the filename has an extra dot beside its extension

**Comment by GentleRock** [comment]
> The issue needs to be reopened as the committed change

I've reported this issue on the main trunk on yt-dlp
https://github.com/yt-dlp/yt-dlp/issues/5526
