### ISSUE TITLE
Merge PR --remux-video

### ISSUE THREAD

**Issue by user0150** [blackjack4494/youtube-dlc#89]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Could you merge this PR? https://github.com/ytdl-org/youtube-dl/pull/25296

**Comment by blackjack4494** [comment]
https://github.com/blackjack4494/youtube-dlc/pull/116

**Comment by user0150** [comment]
Thank you @Zocker1999NET @blackjack4494
