### ISSUE TITLE
Subtitle embed error

### ISSUE THREAD

**Issue by Worzard** [blackjack4494/youtube-dlc#92]
This fork can't embed subtitles whereas the original can. Using this command
**`youtube-dlc -f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best" --write-sub --sub-lang en --embed-subs https://www.youtube.com/watch?v=4yvY-tYh0bM`**
will give the error
**`ERROR: file:The WORST iMac to buy-4yvY-tYh0bM.en.json3: Invalid data found when processing input`**.
I presume it might be because it's not downloading subtitles in the vtt format.

**Comment by blackjack4494** [comment]
Will be fixed very soon https://github.com/blackjack4494/youtube-dlc/issues/33#issuecomment-691626844
